name: 'Emscripten'

on: [push, workflow_dispatch]

jobs:
  Emscripten:
    strategy:
      fail-fast: false
      matrix:
        BuildType: [Release]

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Install Emscripten SDK'
      run: |
        cd ..
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: 'CMake Configuration for Emscripten'
      run: |
        source ../emsdk/emsdk_env.sh
        emcmake cmake -B ../nCine-libraries-build -D CMAKE_BUILD_TYPE=${{ matrix.BuildType }}

    - name: 'Make'
      run: |
        source ../emsdk/emsdk_env.sh
        make -j2 -C ../nCine-libraries-build
        
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: Emscripten
        path: _build
        