name: 'Linux'

env:
  DEPLOY_FILE_NOEXT: nCine-external-OS-COMPILER-VERSION
  DEPLOY_MESSAGE:
    "Push artifact from GitHub Actions build ${{ github.run_number }} with id ${{ github.run_id }}

     - nCine-libraries artifact from branch 'BRANCH_NAME' with commit id ${{ github.sha }}"
  DEPLOY_BRANCH: libraries-OS-COMPILER

on: [push, workflow_dispatch]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        include:
        - BuildType: Release
          CC: gcc
          CXX: g++

        #- BuildType: Release
        #  CC: clang
        #  CXX: clang++

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Install Build Dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libasound2-dev libpulse-dev

    - name: 'CMake Configuration'
      run: |
        export CC=${{ matrix.CC }}
        export CXX=${{ matrix.CXX }}

        cmake -B ../nCine-libraries-build -D CMAKE_BUILD_TYPE=${{ matrix.BuildType }}

    - name: 'Make'
      run: |
        make -j2 -C ../nCine-libraries-build
        
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: ./nCine-external/
       