name: 'macOS'

on: [push, workflow_dispatch]

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        include:
        - BuildType: Release
          ArchName: x64
          ARCH: x86_64
        - BuildType: Release
          ArchName: ARM64
          ARCH: arm64
        #- BuildType: Release
        #  ArchName: Universal
        #  ARCH: arm64;x86_64

    runs-on: 'macOS-latest'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'CMake Configuration'
      run: |
        cmake -B ../nCine-libraries-build -D CMAKE_BUILD_TYPE=${{ matrix.BuildType }} -D CMAKE_OSX_ARCHITECTURES="${{ matrix.ARCH }}" -D BUILD_PNG=OFF

    - name: 'Make'
      run: |
        make -j2 -C ../nCine-libraries-build

    - name: 'Create TAR'
      run: |
        tar cpzf libraries.tar.gz _build
        
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: MacOS_${{ matrix.ArchName }}
        path: libraries.tar.gz
